# Generated by Django 3.0.14 on 2022-06-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
